### ISSUE TITLE
stuff being added to env-vars on mac

### ISSUE THREAD

**Issue by konsumer** [Pytal/deploy-env#22]
I use this tool on linux and it works great. I generate a `.env.preview` file then run `deploy-env preview` and it sets up all the vars correctly.

A co-worker uses mac, and whenever they run same command, they get a generated env file that looks correct, but after it's deployed, I get errors in the vercel log that point me to believing it's a bad env-var. I tried it on my own mac (with the same code) and it had a similar issue. it appears to be adding `-n` and `\n` to the var. I made an endpoint to dump the env-vars as json, and they look like this:

```json
{
  "SOME_VAR": "-n MYVALUE\n"
}
```
when it should be:

```json
{
  "SOME_VAR": "MYVALUE"
}
```

My .env.preview looks like this:

```
SOME_VAR=MYVALUE
```

**Comment by Pytal** [comment]
@konsumer Fix is published in v1.1.4
