### ISSUE TITLE
deploy-env is trimming env

### ISSUE THREAD

**Issue by Guizzoni** [Pytal/deploy-env#25]
I'm using a `.env` file, but if a env var have spaces, `deploy-env` trims them.

For example this env:
`SOME_ENV=Some Important Env `
Would translate to `SomeImportantEnv` when using `deploy-env`. 

Is there a way to fix that? I've already tried using quotes, but it didn't work.

**Comment by Pytal** [comment]
Fix is up in v1.1.6
